from enum import Enum


class LeagueEnum(str, Enum):
    ATP = "atp"
    BUNDESLIGA = "bundesliga"
    COLLEGE_BASEBALL = "college-baseball"
    COLLEGE_FOOTBALL = "college-football"
    CONCACAF_CHAMPIONS = "concacaf.champions"
    ENG_1 = "eng.1"
    ENG_2 = "eng.2"
    ENG_FA = "eng.fa"
    ENG_W_1 = "eng.w.1"
    EPL = "epl"
    ESP_1 = "esp.1"
    ESP_COPA_DEL_REY = "esp.copa_del_rey"
    EUROPA_LEAGUE = "europa-league"
    F1 = "f1"
    GER_1 = "ger.1"
    GER_DFB_POKAL = "ger.dfb_pokal"
    ITA_COPPA_ITALIA = "ita.coppa_italia"
    LALIGA = "laliga"
    LIGUE_1 = "ligue-1"
    LPGA = "lpga"
    MENS_COLLEGE_BASKETBALL = "mens-college-basketball"
    MEX_1 = "mex.1"
    MLB = "mlb"
    MLS = "mls"
    NASCAR_PREMIER = "nascar-premier"
    NBA = "nba"
    NFL = "nfl"
    NHL = "nhl"
    OTHER = "other"
    PGA = "pga"
    POR_1 = "por.1"
    SERIE_A = "serie-a"
    UCL = "ucl"
    UEFA_CHAMPIONS = "uefa.champions"
    UEFA_EUROPA = "uefa.europa"
    UEFA_EUROPA_CONF = "uefa.europa.conf"
    USA_1 = "usa.1"
    USA_NWSL = "usa.nwsl"
    USA_NWSL_CUP = "usa.nwsl.cup"
    WNBA = "wnba"
    WOMENS_COLLEGE_BASKETBALL = "womens-college-basketball"
    WTA = "wta"

    def __str__(self) -> str:
        return str(self.value)
