from enum import Enum


class MlbStatisticName(str, Enum):
    ASSISTS = "assists"
    ATBATS = "atBats"
    AVG = "avg"
    BATTINGAVERAGE = "battingAverage"
    BATTINGAVERAGEAGAINST = "battingAverageAgainst"
    BLOWNSAVES = "blownSaves"
    COMPLETEGAMES = "completeGames"
    DOUBLES = "doubles"
    EARNEDRUNAVERAGE = "earnedRunAverage"
    EARNEDRUNS = "earnedRuns"
    ERA = "ERA"
    ERRORS = "errors"
    FIELDINGPERCENTAGE = "fieldingPercentage"
    GAMESBATTING = "gamesBatting"
    GAMESFIELDING = "gamesFielding"
    GAMESPITCHING = "gamesPitching"
    GAMESPLAYED = "gamesPlayed"
    GAMESSTARTED = "gamesStarted"
    GROUNDINTODOUBLEPLAYS = "groundIntoDoublePlays"
    HITBATSMEN = "hitBatsmen"
    HITS = "hits"
    HITSALLOWED = "hitsAllowed"
    HOLDS = "holds"
    HOMERSPITCHING = "homersPitching"
    HOMERUNS = "homeRuns"
    INNINGSPITCHED = "inningsPitched"
    INTENTIONALWALKS = "intentionalWalks"
    LEFTONBASE = "leftOnBase"
    LOSSES = "losses"
    OBP = "obp"
    ONBASEPERCENTAGE = "onBasePercentage"
    ONBASEPLUSSLUGGING = "onBasePlusSlugging"
    OPS = "ops"
    PICKOFFS = "pickoffs"
    PLATEAPPEARANCES = "plateAppearances"
    PUTOUTS = "putouts"
    RBI = "rbi"
    RUNS = "runs"
    RUNSPITCHING = "runsPitching"
    SACRIFICEBUNTS = "sacrificeBunts"
    SACRIFICEFLIES = "sacrificeFlies"
    SAVEOPPORTUNITIES = "saveOpportunities"
    SAVES = "saves"
    SHUTOUTS = "shutouts"
    SLG = "slg"
    SLUGGINGPERCENTAGE = "sluggingPercentage"
    STOLENBASES = "stolenBases"
    STRIKEOUTS = "strikeouts"
    STRIKEOUTSPITCHING = "strikeoutsPitching"
    TOTALBASES = "totalBases"
    TOTALCHANCES = "totalChances"
    TRIPLES = "triples"
    WALKS = "walks"
    WALKSALLOWED = "walksAllowed"
    WALKSPLUSHITSPERINNINGPITCHED = "walksPlusHitsPerInningPitched"
    WILDPITCHES = "wildPitches"
    WINPERCENTAGE = "winPercentage"
    WINS = "wins"

    def __str__(self) -> str:
        return str(self.value)
