from enum import Enum


class NflStatisticName(str, Enum):
    COMPLETIONATTEMPTS = "completionAttempts"
    DEFENSIVE = "defensive"
    DEFENSIVETOUCHDOWNS = "defensiveTouchdowns"
    FIRSTDOWNS = "firstDowns"
    FIRSTDOWNSPASSING = "firstDownsPassing"
    FIRSTDOWNSPENALTY = "firstDownsPenalty"
    FIRSTDOWNSRUSHING = "firstDownsRushing"
    FOURTHDOWNEFF = "fourthDownEff"
    FUMBLES = "fumbles"
    FUMBLESLOST = "fumblesLost"
    INTERCEPTIONS = "interceptions"
    KICKING = "kicking"
    KICKRETURNS = "kickReturns"
    LOSSES = "losses"
    NETPASSINGYARDS = "netPassingYards"
    OVERALL = "overall"
    PASSING = "passing"
    POINTSAGAINST = "pointsAgainst"
    POINTSFOR = "pointsFor"
    POSSESSIONTIME = "possessionTime"
    PUNTING = "punting"
    PUNTRETURNS = "puntReturns"
    RECEIVING = "receiving"
    REDZONEATTEMPTS = "redZoneAttempts"
    RUSHING = "rushing"
    RUSHINGATTEMPTS = "rushingAttempts"
    RUSHINGYARDS = "rushingYards"
    SACKSYARDSLOST = "sacksYardsLost"
    THIRDDOWNEFF = "thirdDownEff"
    TIES = "ties"
    TOTALDRIVES = "totalDrives"
    TOTALOFFENSIVEPLAYS = "totalOffensivePlays"
    TOTALPENALTIESYARDS = "totalPenaltiesYards"
    TOTALYARDS = "totalYards"
    TURNOVERS = "turnovers"
    WINPERCENT = "winPercent"
    WINS = "wins"
    YARDSPERPASS = "yardsPerPass"
    YARDSPERPLAY = "yardsPerPlay"
    YARDSPERRUSHATTEMPT = "yardsPerRushAttempt"

    def __str__(self) -> str:
        return str(self.value)
